config/routes.rb
Rails.application.routes.draw do
  get 'store/index'
  get "store"  => 'store#index'
  resources :sale_items

end

app/models/sale_item.rb
class SaleItem < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sale_items_controller.rb
class SaleItemsController < ApplicationController
  before_action :set_sale_item, only: [:show, :edit, :update, :destroy]

  # GET /sale_items
  # GET /sale_items.json
  def index
    @sale_items = SaleItem.all
  end

  # GET /sale_items/1
  # GET /sale_items/1.json
  def show
  end

  # GET /sale_items/new
  def new
    @sale_item = SaleItem.new
  end

  # GET /sale_items/1/edit
  def edit
  end

  # POST /sale_items
  # POST /sale_items.json
  def create
    @sale_item = SaleItem.new(sale_item_params)

    respond_to do |format|
      if @sale_item.save
        format.html { redirect_to @sale_item, notice: 'Sale item was successfully created.' }
        format.json { render :show, status: :created, location: @sale_item }
      else
        format.html { render :new }
        format.json { render json: @sale_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sale_items/1
  # PATCH/PUT /sale_items/1.json
  def update
    respond_to do |format|
      if @sale_item.update(sale_item_params)
        format.html { redirect_to @sale_item, notice: 'Sale item was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale_item }
      else
        format.html { render :edit }
        format.json { render json: @sale_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sale_items/1
  # DELETE /sale_items/1.json
  def destroy
    @sale_item.destroy
    respond_to do |format|
      format.html { redirect_to sale_items_url, notice: 'Sale item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale_item
      @sale_item = SaleItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_item_params
      params.require(:sale_item).permit(:name, :price, :item_type, :image_url)
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    # orders the sale items by name
    @sale_items = SaleItem.order(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sale_items_helper.rb
module SaleItemsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mystuff</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sale_items/_form.html.erb
<%= form_for(@sale_item) do |f| %>
  <% if @sale_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale_item.errors.count, "error") %> prohibited this sale_item from being saved:</h2>

      <ul>
      <% @sale_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :item_type %><br>
    <%= f.text_field :item_type %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sale_items/edit.html.erb
<h1>Editing sale_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale_item %> |
<%= link_to 'Back', sale_items_path %>

app/views/sale_items/index.html.erb
<h1>Listing sale_items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Item type</th>
      <th>Image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sale_items.each do |sale_item| %>
      <tr>
        <td><%= sale_item.name %></td>
        <td><%= sale_item.price %></td>
        <td><%= sale_item.item_type %></td>
        <td><%= sale_item.image_url %></td>
        <td><%= link_to 'Show', sale_item %></td>
        <td><%= link_to 'Edit', edit_sale_item_path(sale_item) %></td>
        <td><%= link_to 'Destroy', sale_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale item', new_sale_item_path %>

app/views/sale_items/new.html.erb
<h1>New sale_item</h1>

<%= render 'form' %>

<%= link_to 'Back', sale_items_path %>

app/views/sale_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sale_item.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @sale_item.price %>
</p>

<p>
  <strong>Item type:</strong>
  <%= @sale_item.item_type %>
</p>

<p>
  <strong>Image url:</strong>
  <%= image_tag @sale_item.image_url %>
</p>

<%= link_to 'Edit', edit_sale_item_path(@sale_item) %> |
<%= link_to 'Back', sale_items_path %>

app/views/store/index.html.erb
<h1>Store#index</h1>
<p>Find me in app/views/store/index.html.erb</p>

<h1>Welcome to store selling MyStuff </h1>

<% @sale_items.each do |item| %>
  <div class="entry" style="color:blue;font-size:2em">
    <p><%= item.name %>
      <span class="price" style="color:green"><%= number_to_currency(item.price) %></span>
	  <span class="cat" style="color:green"><%= item.item_type %></span>
	 </p>
  </div>
<% end %>